Chat added
XREAL-SNU/xTown pull request #10
Opened 2021-12-09 06:00 UTC by AliceOfSNU

text chat added

2021-12-09 19:42 UTC, brainini commented
해당 구현 사항 제 local에 pull 해서 확인해봤습니다.
챗 입력 및 채팅방 display까지 잘 작동하고, subscribe를 통해 새로운 채널로 이동하는 것 밑 join을 통해 이전 채널로 이동했을 때 대화내용 남아있는 것 전부 확인했습니다.
단지, 다음 사항이 수정되면 좋을 것 같습니다. 

1. 각 코드에 주석이 필요함. 
2. 현재 실행 시 Chat 기능만 나와 MirrorCAM 기능을 확인하지 못함.
3. Chat 기능 시 현재는 UserID가 ABCD로만 고정이 되어 있어 webGL로 build했을 때 두 user간 소통하는 것을 확인할 수 없음. 새로 채팅방에 들어갈 때 user instance가 새로 생성하게 해야 할 듯.

위의 사항들이 수정되면 자세한 코드리뷰 후에 approve 하도록 하겠습니다.

2021-12-09 20:07 UTC, brainini requested changes
해당 구현 사항 제 local에 pull 해서 확인해봤습니다.
챗 입력 및 채팅방 display까지 잘 작동하고, subscribe를 통해 새로운 채널로 이동하는 것 밑 join을 통해 이전 채널로 이동했을 때 대화내용 남아있는 것 전부 확인했습니다.
단지, 다음 사항이 수정되면 좋을 것 같습니다.

1. 중요한 코드에 주석이 필요함.
2. 현재 실행 시 Chat 기능만 나와 MirrorCAM 기능을 확인하지 못함.
3. Chat 기능 시 현재는 UserID가 ABCD로만 고정이 되어 있어 webGL로 build했을 때 두 user간 소통하는 것을 확인할 수 없음. 새로 채팅방에 들어갈 때 user instance가 새로 생성하게 해야 할 듯.

-> 위의 사항들이 수정되면 자세한 코드리뷰 후에 approve 하도록 하겠습니다.

2021-12-10 04:10 UTC, AliceOfSNU commented
1. 주석을 좀 보강하긴 했습니다. 추가로 코드의 어떤 부분이 설명이 더 필요한지 말씀해주시면 해당 부분 보강설명 하도록 하겠습니다.

2. Mirror cam 은 현재 브랜치에 움직일 수 있는avatar가 없으므로 Game view 가 아닌 Scene view에서만 체크 가능합니다.
![image](https://user-images.githubusercontent.com/86138312/145515555-cf2ce37e-ef27-48b1-93e3-e52f98b43590.png)
저 초록색 trigger가 캡쳐액션 감지 박스입니다. 거기에 scene에 넣어놓은 분홍색 박스를 드래그해서 넣으면 debug.log에 아래와 같이 cam이 준비 되었다는 걸 확인 하실 수 있습니다.
![image](https://user-images.githubusercontent.com/86138312/145515518-4c24af17-3934-4da0-a78d-7d62d0688b23.png)

3. ID는 documentation에 써 놓았듯이 inspector에서 바꿀 수 있습니다. 우선 빌드한 후, 두번째 플레이어는 에디터에서 userid를 바꾸어서 테스트하실 수 있습니다. 원래는 userid는 아바타 속성에서 받아와야 하는 것인데, 일단은 저렇게 테스트해야 될 것 같습니다.

2021-12-10 06:38 UTC, brainini reviewed
코드 리뷰 전체적으로 다 해봤습니다. 해당 사항 확인해주시면 감사하겠습니다.
그리고 혹시 mirror camera와 chat기능을 각각 다른 scene으로 분리할 수 있을까요?
이후에 portal을 이용한 컨텐츠 이동이 주가 될텐데 scene이 분리되 있어야 나중에 더 다른 구현이 더 편할 것 같다는 생각이 들어서요.

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
> +            Connect();
Start()에서 바로 Connect()를 실행하는 것보다는 InputField를 가진 Panel을 하나 더 만들어 Nickname을 입력하면 해당 userID를 가진 User가 Authentication을 가지고 ChatRoom을 여는 것으로 고려하면 좋을 것 같습니다. 
위에서 언급한 한 단계가 더 있다면 후에 아바타를 통한 적용 및 UI/UX적용에 더 용이할 것 같습니다.

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>              if (Input.GetKey(KeyCode.Return) || Input.GetKey(KeyCode.KeypadEnter))
여기에도 및의 `OnClickSend()`에서처럼
```cs
if (this.InputFieldChat != null) {}
```
이 들어가야 하지 않나요?

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>              if (doingPrivateChat)
privateChat 기능은 어떻게 작동하는건지 설명해주실 수 있나요?

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
> +                    else //not yet joined - create a new channel and enter
User a, b가 있다고 할 때 다음 상황이 궁금합니다.
1. a가 ch1이라는 채널을 subscribe했을 때 b가 `\join ch1`를 통해 해당 채널에 join이 가능한지?
2. a가 ch1이라는 채널을 subscribe했을 때 b가 동일한 이름으로 채널을 subscribe하면 어떻게 되는지?

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>                      {
여기에 나와있는 이 기능들의 용도가 잘 이해가 가지 않는데,
클럽 하우스 로비 화면처럼 여러개의 채팅 채널이 있고 원하는 채팅채널을 눌러서 들어갈 수 있는 그런 기능인건가요?

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/CamCapture.cs
> +        File.WriteAllBytes(Application.dataPath + "/Photos/" + FileCounter + ".png", Bytes);
dataPath가 어딘가요?? local에 저장되는 건가요?

2021-12-10 06:38 UTC, brainini commented on Assets/Scripts/CamCapture.cs
> +        FileCounter++;
FileCounter의 용도가 무엇인가요?

2021-12-10 07:16 UTC, AliceOfSNU commented on Assets/Scripts/TextChat/PhotonChatManager.cs
> +                    else //not yet joined - create a new channel and enter
1. join은 내가 subscribe한 채널만 가능합니다. 먼저 해당 channel을 subscribe한후(그럼 지금 로직대로라면 바로 해당 채널에 join) 그 후에 join을 써서 해당 채널로 이동할 수 있습니다
2. 이미 존재하는 채널이므로 구독이 됩니다.

2021-12-10 07:17 UTC, AliceOfSNU commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>                      {
넵 자신이 subscribe해놓은 채널들의 목록이 myChannels입니다. 마치 카톡방 목록이라고 생각하시면 될 것 같습니다.

2021-12-10 07:18 UTC, AliceOfSNU commented on Assets/Scripts/CamCapture.cs
> +        File.WriteAllBytes(Application.dataPath + "/Photos/" + FileCounter + ".png", Bytes);
datapath는 유니티 프로젝트 설정에 기본적으로 들어있는 값입니다. 빌드 시 빌드한 경로로 설정되는 것으로 압니다.

2021-12-10 07:19 UTC, AliceOfSNU commented on Assets/Scripts/CamCapture.cs
> +        FileCounter++;
총 몇개의 캡쳐를 했는지 기록해서 이미지 이름 붙일때 capture1 capture2 이런식입니다

2021-12-10 07:21 UTC, AliceOfSNU commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>              if (doingPrivateChat)
이건 다른 채널과 마찬가지인데 photon chat에서 privateChannels라는 목록에 private한 채널들을 별도로 보관합니다. 이때, 채널 이름이 source:destination인데 destination부분을 sendTarget으로 지정해서 거기에 메시지를 보내야 합니다. documentation에 써있듯 provate chat은 지금은 지원되지 않습니다. 해당 코드는 프라이빗이 아니라는 것을 확인하는 용도로만 사용됩니다

2021-12-10 07:23 UTC, AliceOfSNU commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>              if (Input.GetKey(KeyCode.Return) || Input.GetKey(KeyCode.KeypadEnter))
그렇네요 수정하겠습니다

2021-12-10 09:05 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
> +                    else //not yet joined - create a new channel and enter
ch1이라는 새로운 채널을 subscribe했을 떄 다음의 3가지 과정이 동시에 일어나는게 맞나요?
1. ch1 채널 생성
2. ch1 채널 구독
3. ch1 채널 join

위와 같이 되고 만약에 다른 유저인 b가 ch1에 join하고 싶다면
1. ch1 구독
2. ch1 채널 join

위의 두 과정을 하는게 맞나요?

2021-12-10 09:07 UTC, brainini commented on Assets/Scripts/TextChat/PhotonChatManager.cs
>                      {
그렇군요 이후에 해당 기능 이용하면 여러가지 재미있는 UI/UX 기능을 만들 수 있겠네요

2021-12-18 07:30 UTC, AliceOfSNU commented on Assets/Scripts/TextChat/PhotonChatManager.cs
> +                    else //not yet joined - create a new channel and enter
1) ch1이라는 새로운 채널을 subscribe하면 1,2만 이루어집니다. join은 \join 메시지를 입력하지 않는 한 실행되지 않습니다
2) 네, 원칙적으로는 두 과정을 하는 게 맞지만, join만 해도 자동으로 subscribe되도록 구현했습니다

2021-12-18 07:32 UTC, AliceOfSNU commented
> 코드 리뷰 전체적으로 다 해봤습니다. 해당 사항 확인해주시면 감사하겠습니다. 그리고 혹시 mirror camera와 chat기능을 각각 다른 scene으로 분리할 수 있을까요? 이후에 portal을 이용한 컨텐츠 이동이 주가 될텐데 scene이 분리되 있어야 나중에 더 다른 구현이 더 편할 것 같다는 생각이 들어서요.

일단 다른 Scene을 새로 만들기보다는, mirror cam이 이미 prefab으로 되어 있으므로 그냥 Scene에서 제외했습니다. (기능마다 scene을 만들면 너무 프로젝트가 커질 것 같아서요) 괜찮을까요?

2021-12-27 11:50 UTC, brainini approved these changes

2022-01-11 11:07 UTC, closed without merging