Photon PUN2 서버를 이용한 간단한 Clicker game 구현
XREAL-SNU/xTown pull request #14
Opened 2021-12-09 20:05 UTC by brainini

## photon OnSerializedView를 이용한 간단한 Clicker game 구현.
- Clicker game scene을 따로 구현. 
- 거지키우기 게임을 모티브
- run하고 닉네임을 입력하면 게임 방이 자동으로 만들어지고 다른 곳(ex. webGL)에서 run했을 때 다른 닉네임을 치면 다른 유저로 접속 가능.
- 기본적으로 click했을 때 점수가 2씩 오름.
- 점수를 Cost로 지불해 upgrade하는 두 가지 방법 제시
    - 누를 때마다 오르는 점수 증가. upgrade할수록 Cost 증가 비율이 커지고, 클릭 증가 비율도 2배로 커짐.
    - 1초마다 자동으로 오르는 점수 증가. upgrade할수록 Cost 증가 비율이 커지고, 초마다 자동으로 오르는 점수 2배로 증가. 

> 주석처리를 일일히 하지는 못했지만 우선 풀리퀘 보냅니다. 부족한 기능이라던가 추가해야할 것 같다 싶은 게 있으면 말씀해주시고, 주석이 필요한 부분을 말씀해주시면 주석 달겠습니다.

2021-12-12 06:01 UTC, Abecid approved these changes
xTown에서 할 수 있는 다양한 게임 중 하나가 될 수 있을 것 같네요

2021-12-13 04:17 UTC, AliceOfSNU commented on Assets/NetworkManager.cs
> +        PhotonNetwork.LocalPlayer.NickName = NicknameInput.text;
Null check

2021-12-13 04:23 UTC, AliceOfSNU commented on Assets/NetworkManager.cs
> +
numeric literals in script: macro를 정의하는게 좋아보여요

2021-12-13 04:24 UTC, AliceOfSNU commented on Assets/NetworkManager.cs
> +
마찬가지로 코드에 상수를 바로 넣는 것보단 macro를 정의하는게 좋아보여요

2021-12-13 04:25 UTC, AliceOfSNU commented on Assets/NetworkManager.cs
> +    void ValuePerSecond()
함수가 실제로 하는 일이 value를 바꾸는 일이므로
UpdateValue 같은 네이밍이 좋을 것 같아요

2021-12-13 04:30 UTC, AliceOfSNU commented on Assets/NetworkManager.cs
> +        CurPanel.SetActive(true);
어차피 Showpanel을 RoomPanel외에 호출하지 않는데 함수로 안만들어도 될 것 같으나, 패널들이 추가될 예정이면 이렇게 놔둬도 괜찮을 것 같아요

2021-12-13 04:39 UTC, AliceOfSNU requested changes
수정요청
1) NetworkManager script가 Game logic 까지 담당하고 있습니다. 단일책임원칙에 비추어, GameController 클래스를 추가하여 NetworkManager로 부터 player를 받아 게임로직(업그레이드, 점수표시 등)을 처리하도록 하는 것이 좋아 보입니다.(이때 NetworkManager, GameController 등은 모두 singleton으로 짜는게 좋습니다)

2) Player 객체에 Null check가 필요합니다(NullReferenceException: Object reference is not set to an instance of ....  어쩌고를 안 보려면 ㅠ)

2021-12-13 05:49 UTC, AliceOfSNU commented
https://ivorycirrus.github.io/TIL/csharp-singleton/

2021-12-13 13:22 UTC, Hyewon0309 commented on Assets/NetworkManager.cs
> +        }
Player.value가 Player.clickUpgradeCost 보다 작은 경우 돈이 부족하다는 메세지를 띄우면 좋을 것 같습니다!

2021-12-13 13:22 UTC, Hyewon0309 commented on Assets/NetworkManager.cs
> +        }
여기도 마찬가지로 돈이 부족하다는 메세지를 추가했으면 좋겠습니다!

2021-12-15 09:04 UTC, brainini commented on Assets/NetworkManager.cs
> +
매크로는 오류가 발생할 가능성이 크므로 C#에서는 매크로를 사용할 수 없으며 더 안전한 방식이 사용됩니다. (https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/compiler-options/language)

위의 상황을 참고하여 매크로를 사용하지는 않았고 따로 변수를 설정해서 해줬습니다.

2021-12-15 09:07 UTC, brainini commented on Assets/NetworkManager.cs
> +
위의 사안이랑 같으므로 resolve처리 해놓겠습니다!

2021-12-15 09:16 UTC, brainini commented on Assets/NetworkManager.cs
> +        }
현재는 혜원님께서 말씀하신 경우에는 button의 interactable을 이용하여 색깔 자체를 희미하게 하고 있다가 Player.value가 더 커질 경우 button의 색이 뚜렷하게 바뀌는 걸 이용하여 user들에게 직관적인 visual recognition을 주고 있는데 메시지가 따로 필요 없지 않을까요?

2021-12-16 04:12 UTC, AliceOfSNU approved these changes

2021-12-16 04:15 UTC, AliceOfSNU commented
그 단일책임원칙은 코드가 길어졌을때나 재사용되는 코드가 많을 때엔 꼭 필요하지만 지금 코드 정도에서는 필수가 아닌 것 같고, 당장은 best practice를 따지는 것보다 생산성이 우선인 것 같아 위 코드 comment에 적힌 change들만 부탁드리고, approve 했습니다!

2021-12-16 07:54 UTC, brainini commented
> 사실 저도 해당사항때문에 고민하고 있었습니다. 단일책임원칙 저도 찾아보고 singleton찾아봤는데 아무래도 이런 짧은코드에서 나누는 것이 비효율적으로 느껴져 고민하던 참이었는데 approve해주셔서 감사합니다 ㅎㅎ



> 그 단일책임원칙은 코드가 길어졌을때나 재사용되는 코드가 많을 때엔 꼭 필요하지만 지금 코드 정도에서는 필수가 아닌 것 같고, 당장은 best practice를 따지는 것보다 생산성이 우선인 것 같아 위 코드 comment에 적힌 change들만 부탁드리고, approve 했습니다!

2021-12-16 09:38 UTC, Hyewon0309 commented on Assets/NetworkManager.cs
> +        }
앗 넵 그렇다면 별로 필요없을 것 같네요!

2021-12-22 08:21 UTC, merged